Add OnboardingPersistancy tests
Bachtanek/GitHub_Learning pull request #19
Opened 2020-12-18 11:28 UTC by Bachtanek

2020-12-18 11:43 UTC, ashhanai requested changes

2020-12-18 11:43 UTC, ashhanai commented on GitHub_LearningTests/Generic/OnboardingPersistancy/Resources/OnboardingResourceTests.swift
> +        XCTAssert(localStorage.isOnboardingFinished == isFinished)
Tento test nedava smyls, protoze kdyby jsi nastail `isFinished` na false, tak ti to neprojde, i kdyz se ten test tvari ze jo.

2020-12-18 11:43 UTC, ashhanai commented on GitHub_LearningTests/Generic/OnboardingPersistancy/Resources/OnboardingResourceTests.swift
> +        let _ = try sut.loadIsOnboardingFinished()
V tomto testu bych radsi predaval dummy co ma vracet a pak to kontroloval s tim, co ti vratit sut.

2020-12-18 11:43 UTC, ashhanai commented on GitHub_LearningTests/Generic/OnboardingPersistancy/Resources/OnboardingResourceTests.swift
> +    func test_givenOnboardingResource_whenloadIsOnboardingFinished_thenDataAreLoaded() throws {
```suggestion
    func test_givenOnboardingResource_whenLoadIsOnboardingFinished_thenDataAreLoaded() throws {
```

2020-12-18 11:43 UTC, ashhanai commented on GitHub_LearningTests/Generic/OnboardingPersistancy/Resources/OnboardingResourceTests.swift
> +        XCTAssert(localStorage.isOnboardingFinished == isFinished)
Bud kontroluj ze se to na tom vola a nebo primo tu hodnotu co se ulozila.

2020-12-18 14:22 UTC, ashhanai requested changes

2020-12-18 14:22 UTC, ashhanai commented on GitHub_LearningTests/Generic/OnboardingPersistancy/Resources/OnboardingResourceTests.swift
> +        localStorage.dataLoaded = isFinished
dataLoaded maji testovat jestli se volalo loaded ne co se vraci. Ten isFinished predavej v initu jako navratovou hodnotu load data fukce.

2020-12-19 16:49 UTC, Bachtanek commented on GitHub_LearningTests/Generic/OnboardingPersistancy/Resources/OnboardingResourceTests.swift
> +        localStorage.dataLoaded = isFinished
Nevim jestli tě chápu ale zkusim.

2020-12-26 16:05 UTC, ashhanai approved these changes

2020-12-26 16:05 UTC, ashhanai commented on GitHub_LearningTests/Generic/OnboardingPersistancy/Resources/OnboardingResourceTests.swift
> +        XCTAssert(localStorage.isDataLoaded == true)
Tento test je zbytecny, ale jinak je to to co jsem chtel :)

2020-12-26 16:06 UTC, ashhanai commented on GitHub_LearningTests/Generic/OnboardingPersistancy/Resources/OnboardingResourceTests.swift
> +        XCTAssert(localStorage.isDataLoaded == true)
Megnu ti to a pak si to nekdy smaz. Dam ti to do issues.

2020-12-26 16:06 UTC, merged